sf=1x

db=dm
classname=dm.jdbc.driver.DmDriver
username=hybench
password=hybench
url=jdbc:dm://172.16.3.244:5236

url_ap=jdbc:dm://172.16.3.244:5236
classname_ap=dm.jdbc.driver.DmDriver
username_ap=hybench
password_ap=hybench

at1_percent=35
at2_percent=25
at3_percent=15
at4_percent=15
at5_percent=7
at6_percent=3

tpclient=1
apclient=1

fresh_interval=20
contention_num=100

apRunMins=1
tpRunMins=1
xpRunMins=1

xtpclient=1
xapclient=1

risk_rate=0.1

dist=uniform
power_alpha=0.1

apround=1
