sf=1x

db=A1
classname=oracle.jdbc.OracleDriver
username=hybench
password=hybench
url=jdbc:oracle:thin:@//192.168.122.1:1521/ORCLPDB1

url_ap=jdbc:oracle:thin:@//192.168.122.1:1521/ORCLPDB1
classname_ap=oracle.jdbc.OracleDriver
username_ap=hybench
password_ap=hybench

at1_percent=35
at2_percent=25
at3_percent=15
at4_percent=15
at5_percent=7
at6_percent=3

tpclient=1
apclient=5

fresh_interval=20
contention_num=100

apRunMins=1
tpRunMins=1
xpRunMins=1

xtpclient=1
xapclient=1

risk_rate=0.1

dist=uniform
power_alpha=0.1

apround=1
