sf=1x

db=
classname=
username=hybench
password=hyBench_0
url=jdbc:oracle:thin:@//oracle_server:1521/ORCLPDB1

url_ap=jdbc:oracle:thin:@//oracle_server:1521/ORCLPDB1
classname_ap=
username_ap=hybench
password_ap=hyBench_0

at1_percent=35
at2_percent=25
at3_percent=15
at4_percent=15
at5_percent=7
at6_percent=3

tpclient=1
apclient=1

fresh_interval=20
contention_num=100

apRunMins=1
tpRunMins=1
xpRunMins=1

xtpclient=1
xapclient=1

risk_rate=0.1

dist=uniform
power_alpha=0.1

apround=1
