


LOAD DATA INFILE '/home/ysdb/hybench/Data_1x/customer.csv' FIELDS TERMINATED BY ',' INTO TABLE customer(CUSTID,COMPANYID,GENDER,NAME,AGE,PHONE,PROVINCE,CITY,LOAN_BALANCE,S_CREDIT,C_CREDIT,B_CREDIT,ISBLOCKED,CREATED_DATE,LAST_UPDATE_TIMESTAMP)

LOAD DATA INFILE '/home/ysdb/hybench/Data_1x/company.csv' FIELDS TERMINATED BY ',' INTO TABLE company(COMPANYID,NAME,CATEGORY,STAFF_SIZE,LOAN_BALANCE,PHONE,PROVINCE,CITY,SAVINGCREDIT,CHECKINGCREDIT,LOANCREDIT,ISBLOCKED,CREATED_DATE,LAST_UPDATE_TIMESTAMP) 
		   
LOAD DATA INFILE '/home/ysdb/hybench/Data_1x/transfer.csv' FIELDS TERMINATED BY ',' INTO TABLE  transfer(ID,SOURCEID,TARGETID,AMOUNT,TYPE,TIMESTAMP,FRESH_TS)  

LOAD DATA INFILE '/home/ysdb/hybench/Data_1x/checking.csv' FIELDS TERMINATED BY ',' INTO TABLE  checking(ID,SOURCEID,TARGETID,AMOUNT,TYPE,TIMESTAMP)

LOAD DATA INFILE '/home/ysdb/hybench/Data_1x/checkingAccount.csv' FIELDS TERMINATED BY ',' INTO TABLE checkingaccount(ACCOUNTID,USERID,BALANCE,ISBLOCKED,TIMESTAMP)

LOAD DATA INFILE '/home/ysdb/hybench/Data_1x/savingAccount.csv' FIELDS TERMINATED BY ',' INTO TABLE savingaccount(ACCOUNTID,USERID,BALANCE,ISBLOCKED,TIMESTAMP)

LOAD DATA INFILE '/home/ysdb/hybench/Data_1x/loanApps.csv' FIELDS TERMINATED BY ',' INTO TABLE loanapps(ID,APPLICANTID,AMOUNT,DURATION,STATUS,TIMESTAMP)

LOAD DATA INFILE '/home/ysdb/hybench/Data_1x/loanTrans.csv' FIELDS TERMINATED BY ',' INTO TABLE loantrans(ID,APPLICANTID,APPID,AMOUNT,STATUS,TIMESTAMP,DURATION,CONTRACT_TIMESTAMP,DELINQUENCY)  


