

LOAD DATA INFILE '/home/ysdb/hybench/Data_1x/customer.csv' FIELDS TERMINATED BY ',' INTO TABLE customer(CUSTID,COMPANYID,GENDER,NAME,AGE,PHONE,PROVINCE,CITY,LOAN_BALANCE,S_CREDIT,C_CREDIT,B_CREDIT,ISBLOCKED,CREATED_DATE,LAST_UPDATE_TIMESTAMP)
