
LOAD DATA INFILE '/home/ysdb/hybench/Data_1x/company.csv' FIELDS TERMINATED BY ',' INTO TABLE company(COMPANYID,NAME,CATEGORY,STAFF_SIZE,LOAN_BALANCE,PHONE,PROVINCE,CITY,SAVINGCREDIT,CHECKINGCREDIT,LOANCREDIT,ISBLOCKED,CREATED_DATE,LAST_UPDATE_TIMESTAMP) 


